version: '3.1'
services:
  mysql:
    restart: "no"
    image: mysql:5.7.16
    container_name: mysql
    volumes:
      #      数据库还原目录 可将需要还原的sql文件放在这里
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306