version: '3.1'
services:
  mysql_master:
    image: mysql:5.7.16
    env_file:
      - ./config/mysql.env
    container_name: "mysql_master"
    restart: "no"
    ports:
      - 3307:3306
    volumes:
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - ./sql:/docker-entrypoint-initdb.d
      - ./config/master/mysql.cnf:/etc/mysql/mysql.cnf
    networks:
      - overlay

  mysql_slave1:
    image: mysql:5.7.16
    env_file:
      - ./config/mysql.env
    container_name: "mysql_slave1"
    restart: "no"
    ports:
      - 3308:3306
    depends_on:
      - mysql_master
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./config/slave1/mysql.cnf:/etc/mysql/mysql.cnf
    networks:
      - overlay

  mysql_slave2:
    image: mysql:5.7.16
    env_file:
      - ./config/mysql.env
    container_name: "mysql_slave2"
    restart: "no"
    ports:
      - 3309:3306
    depends_on:
      - mysql_master
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./config/slave2/mysql.cnf:/etc/mysql/mysql.cnf
    networks:
      - overlay

networks:
  overlay: